// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvxwfabmqkwspxourezn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2eHdmYWJtcWt3c3B4b3VyZXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzEzMTgsImV4cCI6MjA3MzEwNzMxOH0.1DSSk2_k1Yl1KonUyYm0rwzbQTCFGNmyNB4x9ArA-h8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});